### ISSUE TITLE
[Bug]: Character encoding breaks attribution text

### ISSUE THREAD

**Issue by JackWH** [swisnl/filament-backgrounds#6]
### What happened?

Using apostrophes or quotes in attribution breaks character encoding

### How to reproduce the bug

Set attribution to something like : `'Today\'s image by "Example"'`.

The attribution will render as: `Today&#039;s image by &quot;Example&quot;`

![Screenshot 2023-12-05 at 18 33 31@2x](https://github.com/swisnl/filament-backgrounds/assets/627533/daaf29f4-3411-41cd-aead-3013470b60c2)

### Package Version

1.1.0

### PHP Version

8.3.0

### Laravel Version

10.34.2

### Which operating systems does with happen with?

macOS, Windows, Linux

### Notes

This is an awesome package, thanks for releasing! Just letting you know about one small issue. Cheers 👌

**Comment by JaZo** [comment]
Thanks, fixed in [1.1.1](https://github.com/swisnl/filament-backgrounds/releases/tag/1.1.1)!
