### ISSUE TITLE
[Bug]: Cache Image per FilamentPanel

### ISSUE THREAD

**Issue by eelco2k** [swisnl/filament-backgrounds#8]
### What happened?

When having multiple Filament Panels the same cached image returns for each panel. even though i've registered another imageProvider

### How to reproduce the bug

create multiple filament panels 

one panel add 
```
$panel->plugin([FilamentBackgroundsPlugin::make()->remember(60)]
```

other panel add:
```
$panel2->plugin([FilamentBackgroundsPlugin::make()->imageProvider(Triangles::make())->remember(60)]
```

open both panels with login page.

proposed update: 

in FilamentBackgroundsPlugin.php change this function so that it gets the correct cached image per filament panel:

```

protected function getImage(): Image
    {

        return Cache::remember(
            Filament::getCurrentPanel()->getId() ?? '' . 'filament-backgrounds:image',
            $this->ttl,
            fn () => ($this->imageProvider ?? CuratedBySwis::make())->getImage()
        );
    }

```

### Package Version

1.1.1

### PHP Version

8.3.2

### Laravel Version

10

**Comment by JaZo** [comment]
Good catch, thanks for reporting! Fixed in [1.1.2](https://github.com/swisnl/filament-backgrounds/releases/tag/1.1.2).
